=== suyogsakegaonkar/hybrid-framework/src/main/resources/xsd/DataSet.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/DataSet" xmlns:tns="http://www.example.org/DataSet" elementFormDefault="qualified">

	<element name="pageData">
		<complexType>
			<sequence>
				<element name="loginDetails" type="tns:loginDetails" maxOccurs="unbounded" minOccurs="0" />
				<element name="comments" type="tns:comments" maxOccurs="unbounded" minOccurs="0"/>
			</sequence>
		</complexType>
	</element>

	<complexType name="loginDetails">
		<sequence>
			<element name="username" type="string" />
			<element name="password" type="string" />
		</sequence>
		<attribute name="id" type="ID"></attribute>
	</complexType>

	<complexType name="comments">
		<sequence>
			<element name="statement" type="string" />
		</sequence>
		<attribute name="id" type="ID"></attribute>
	</complexType>

</schema>

=== suyogsakegaonkar/hybrid-framework/target/classes/xml/Data.xml
<?xml version="1.0"?>

<pageData xmlns="http://www.example.org/DataSet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/DataSet ../src/test/resources/xsd/DataSet.xsd ">

	<loginDetails id="facebook">
		<username>suyogsakegaonkar@facebook.com</username>
		<password>testfacebook</password>
	</loginDetails>
	<loginDetails id="gmail">
		<username>suyogsakegaonkar@gmail.com</username>
		<password>testgmail</password>
	</loginDetails>

	<comments id="comment_1">
		<statement>Suyog is a Automation Engineer.</statement>
	</comments>

</pageData>
